### ISSUE TITLE
related project

### ISSUE THREAD

**Issue by yarikoptic** [Brainhack-Proceedings-2015/Dery_HBM_ClubsOfScience#1]
may be you would like to mention somewhat related project which i am not sure if any longer exists, http://scinet.osf.io/ and see e.g. http://hairycode.org/2014/01/15/osf-scinet-goes-public-beta/ for one of the announcements.

**Comment by sderygithub** [comment]
Thank you @yarikoptic ,
Really not nice of me to have let this project slip my mind.
Added mentions of this project and Neurotree as well for completeness :)
